package com.example.greendaolearning.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaolearning.model.Test0;

import com.example.greendaolearning.greendao.Test0Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig test0DaoConfig;

    private final Test0Dao test0Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        test0DaoConfig = daoConfigMap.get(Test0Dao.class).clone();
        test0DaoConfig.initIdentityScope(type);

        test0Dao = new Test0Dao(test0DaoConfig, this);

        registerDao(Test0.class, test0Dao);
    }
    
    public void clear() {
        test0DaoConfig.clearIdentityScope();
    }

    public Test0Dao getTest0Dao() {
        return test0Dao;
    }

}
